#!/bin/bash
#
# A rofi powered menu to execute power related action.
# Uses: amixer mpc poweroff reboot rofi rofi-prompt

POWER_OFF=""
REBOOT=""
LOCK=""
SUSPEND=""
LOG_OUT=""
yes=''
no=''


confirm() {
	echo -e "$yes\n$no" | confirm_cmd

}

confirm_cmd() {
       	rofi -dmenu \
		-p 'Confirmation' \
		-mesg 'Are you Sure ?' \
		-theme /home/picsu/.config/rofi/prompt/prompt.rasi
}

chosen=$(echo -e "$POWER_OFF\n$REBOOT\n$LOCK\n$SUSPEND\n$LOG_OUT" \
    | rofi -theme-str '@import "/home/picsu/.config/rofi/power/power.rasi"' \
           -dmenu \
           -selected-row 1)

case "$chosen" in
    "$POWER_OFF")
	if [[ "$(confirm)" == "$yes" ]]; then
    	     systemctl poweroff
	else
		exit 0
	fi
        ;;

    "$REBOOT")
	if [[ "$(confirm)" == "$yes" ]]; then
    	     systemctl reboot
	else
		exit 0

	fi
        ;;

    "$LOCK")
        # TODO Add your lockscreen command.
	xsecurelock
        ;;

    "$SUSPEND")
        # Pause music and mute volume before suspending.
        mpc --quiet pause
        amixer set Master mute
        # TODO Add your suspend command.
    	systemctl suspend
        ;;

    "$LOG_OUT")
        # TODO Add your log out command.
	bspc quit
	;;

    *) exit 1 ;;
esac
